name: weathery
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^8.0.1

  #Graphics
  shimmer: ^2.0.0
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^5.0.6996

  # Network
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  retrofit_generator: ^4.0.3
  dio_cache_interceptor: ^3.3.0
  dio_logger: ^4.0.8+8
  http: ^0.13.0

  # Annotation
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0

  #DI
  get_it: ^7.2.0
  injectable: ^1.5.3
  injectable_generator: ^1.5.4

  #Storage
  shared_preferences: ^2.0.15
  hive: ^2.0.5
  hive_flutter: ^1.1.0

  #Routing
  auto_route: ^5.0.1

  #Utils
  intl: ^0.17.0
  dartz: ^0.10.1
  cached_network_image: ^3.2.1
  connectivity_plus: ^2.3.6+1
  logger: ^1.1.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  hive_generator: ^1.1.2
  flutter_native_splash: ^2.2.7
  auto_route_generator: ^5.0.2
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  flutter_launcher_icons: ^0.10.0


flutter:
  uses-material-design: true

  assets:
      - .env